NAME = libc
SRCS = $(shell find src/ -name "*.c" -o -name "*.S" -o -name "*.cpp")
CFLAGS += -Wno-implicit-int -Wno-implicit-function-declaration -Wno-int-conversion -fcommon

include $(NAVY_HOME)/Makefile.lib
